name: CMake

on:
  push:
    branches: [ 03.Fractal ]
  pull_request:
    branches: [ 03.Fractal ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -S ${{github.workspace}}/03.Fractal -B ${{github.workspace}}/03.Fractal/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/03.Fractal/build --config ${{env.BUILD_TYPE}}